### ISSUE TITLE
Add AI competitions

### ISSUE THREAD

**Issue by salvador-dali** [owainlewis/awesome-artificial-intelligence#11]
This is not an issue, but rather a suggestion:

It would be nice to see programming competitions, where one should write an AI to compete against another another AI (or work together to create something). Up till now I have seen only:

 - http://www.battlecode.org/ which runs once per year
 - http://helloworldopen.com/
 - http://aichallenge.org/

**Comment by owainlewis** [comment]
Thank you. I wasn't really aware of these and they make a good addition. :+1:

**Comment by Inoryy** [comment]
@owainlewis another great one is http://theaigames.com/

**Comment by owainlewis** [comment]
Thanks :+1: Will add that in now
