### ISSUE TITLE
List of movies with AI as the main focus

### ISSUE THREAD

**Issue by tomzx** [owainlewis/awesome-artificial-intelligence#12]
I see you have two images of Ex Machina in the README file.

I was thinking it'd be interesting to have a list of movies that have AI as their main focus. I see movies as similar to philosophy in the sense that they present you with a topic and make you think about it.

What do you think?

**Comment by owainlewis** [comment]
Yeah actually thought the same thing myself. Feel free to submit a PR if you have any ideas. Thanks :+1:

**Comment by tomzx** [comment]
Submitted #13.
