### ISSUE TITLE
Modify Repository name 

### ISSUE THREAD

**Issue by MohamedDiaa** [owainlewis/awesome-artificial-intelligence#18]
in most awesome lists on  github 
they use Education postfix to differentiate between list of courses and list of libraries and code
- awesome-swift    (SDK and libraries)
- awesome-swift-education   (Courses and lectures)

I suggest to change name of reprository
from "awesome-artificial-intelligence"   ->  "awesome-artificial-intelligence-education"

**Comment by owainlewis** [comment]
Thanks. I'm happy to keep it as is for now. If there are any others that want to change the name I may reconsider. Thanks :+1:
