### ISSUE TITLE
Dead link under Programs

### ISSUE THREAD

**Issue by hosterho** [owainlewis/awesome-artificial-intelligence#31]
Under rubric "Programming" the link to the PDF of the resource 

> `AI Algorithms, Data Structures and Idioms in Prolog, Lisp and Java`**`- PDF here`**

 is leading to 404 error of Dropbox. The resource does not seem to exist anymore or the location may have changed. It would be great if you could check and repair it.

**Comment by Argoniton** [comment]
Hi! That is what you are looking for
[AI Algorithms, Data Structures and Idioms in Prolog, Lisp and Java](http://wps.aw.com/wps/media/objects/5771/5909832/PDF/Luger_0136070477_1.pdf)

**Comment by hosterho** [comment]
Thanks! 
I think it would be great if someone could change the underlying link behind the link text to the new location.
